import 'dart:io';
import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/wood_component.dart';
import '../services/company_service.dart';
import '../providers/auth_provider.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class CftPdfGenerator {
  // Save to Downloads folder
  static Future<File> _saveToDownloads(
      Uint8List bytes, String fileName) async {
    try {
      Directory? downloadsDir;

      if (Platform.isAndroid) {
        downloadsDir = Directory('/storage/emulated/0/Download');
        if (!await downloadsDir.exists()) {
          downloadsDir = await getExternalStorageDirectory();
        }
      } else {
        downloadsDir = await getApplicationDocumentsDirectory();
      }

      downloadsDir ??= await getApplicationDocumentsDirectory();

      if (!await downloadsDir.exists()) {
        await downloadsDir.create(recursive: true);
      }

      final file = File('${downloadsDir.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file;
    } catch (e) {
      final appDir = await getApplicationDocumentsDirectory();
      final file = File('${appDir.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file;
    }
  }

  static Future<File> generate({
    required List<WoodComponent> components,
    required String reportTitle,
    BuildContext? context,
  }) async {
    final pdf = await _createPDF(
        components: components,
        reportTitle: reportTitle,
        context: context);
    final bytes = await pdf.save();
    final fileName =
        'WoodRatePro_CFT_${DateFormat('ddMMyyyy_HHmm').format(DateTime.now())}.pdf';
    return _saveToDownloads(bytes, fileName);
  }

  static Future<Uint8List> generateBytes({
    required List<WoodComponent> components,
    required String reportTitle,
    BuildContext? context,
  }) async {
    final pdf = await _createPDF(
        components: components,
        reportTitle: reportTitle,
        context: context);
    return pdf.save();
  }

  // Share via WhatsApp or any app
  static Future<void> shareCftReport({
    required List<WoodComponent> components,
    required String reportTitle,
    BuildContext? context,
  }) async {
    final bytes = await generateBytes(
        components: components,
        reportTitle: reportTitle,
        context: context);
    final tempDir = await getTemporaryDirectory();
    final fileName =
        'WoodRatePro_CFT_${DateFormat('ddMMyyyy_HHmm').format(DateTime.now())}.pdf';
    final file = File('${tempDir.path}/$fileName');
    await file.writeAsBytes(bytes);

    final totalCft =
    components.fold<double>(0, (sum, c) => sum + c.cft);

    await Share.shareXFiles(
      [XFile(file.path)],
      text:
      'CFT Report: $reportTitle\nTotal CFT: ${totalCft.toStringAsFixed(2)}\nGenerated by WoodRate Pro',
      subject: 'CFT Report - $reportTitle',
    );
  }

  static Future<pw.Document> _createPDF({
    required List<WoodComponent> components,
    required String reportTitle,
    BuildContext? context,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd-MM-yyyy HH:mm');

    // Load company details
    String companyName = 'WoodRate Pro';
    String companyAddress = '';
    String companyPhone = '';
    String companyGstin = '';

    if (context != null) {
      try {
        final authProvider =
        Provider.of<AuthProvider>(context, listen: false);
        final company = authProvider.currentCompany;
        if (company != null) {
          companyName = company.companyName;
          companyAddress = company.address;
          companyPhone = company.phone;
          companyGstin = company.gstin ?? '';
        }
      } catch (e) {
        // use defaults
      }
    }

    double totalCft =
    components.fold<double>(0, (sum, c) => sum + c.cft);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return [
            // ═══════════════════════════════════
            // HEADER
            // ═══════════════════════════════════
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(20),
              decoration: pw.BoxDecoration(
                gradient: const pw.LinearGradient(
                  colors: [PdfColors.blue800, PdfColors.blue600],
                ),
                borderRadius: pw.BorderRadius.circular(12),
              ),
              child: pw.Row(
                mainAxisAlignment:
                pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment:
                      pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          companyName,
                          style: pw.TextStyle(
                            fontSize: 22,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.white,
                          ),
                        ),
                        if (companyPhone.isNotEmpty) ...[
                          pw.SizedBox(height: 4),
                          pw.Text(
                            'Ph: $companyPhone',
                            style: const pw.TextStyle(
                              fontSize: 10,
                              color: PdfColors.white,
                            ),
                          ),
                        ],
                        if (companyAddress.isNotEmpty) ...[
                          pw.SizedBox(height: 4),
                          pw.Text(
                            companyAddress,
                            style: const pw.TextStyle(
                              fontSize: 10,
                              color: PdfColors.white,
                            ),
                          ),
                        ],
                        if (companyGstin.isNotEmpty) ...[
                          pw.SizedBox(height: 4),
                          pw.Text(
                            'GSTIN: $companyGstin',
                            style: const pw.TextStyle(
                              fontSize: 10,
                              color: PdfColors.white,
                            ),
                          ),
                        ],
                      ],
                    ),
                  ),
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(
                        horizontal: 16, vertical: 8),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.white,
                      borderRadius: pw.BorderRadius.circular(8),
                    ),
                    child: pw.Column(
                      children: [
                        pw.Text(
                          'CFT REPORT',
                          style: pw.TextStyle(
                            fontSize: 14,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.blue800,
                          ),
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(
                          'WoodRate Pro',
                          style: pw.TextStyle(
                            fontSize: 9,
                            color: PdfColors.blue600,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 16),

            // ═══════════════════════════════════
            // REPORT INFO
            // ═══════════════════════════════════
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey50,
                borderRadius: pw.BorderRadius.circular(8),
                border:
                pw.Border.all(color: PdfColors.grey300),
              ),
              child: pw.Row(
                mainAxisAlignment:
                pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment:
                    pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        reportTitle,
                        style: pw.TextStyle(
                          fontSize: 14,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blue800,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        'Generated: ${dateFormat.format(DateTime.now())}',
                        style: const pw.TextStyle(fontSize: 10),
                      ),
                      pw.SizedBox(height: 2),
                      pw.Text(
                        'Total Components: ${components.length}',
                        style: pw.TextStyle(
                          fontSize: 10,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(
                        horizontal: 20, vertical: 12),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.blue800,
                      borderRadius: pw.BorderRadius.circular(8),
                    ),
                    child: pw.Column(
                      children: [
                        pw.Text(
                          'TOTAL CFT',
                          style: pw.TextStyle(
                            fontSize: 10,
                            color: PdfColors.blue100,
                          ),
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(
                          totalCft.toStringAsFixed(2),
                          style: pw.TextStyle(
                            fontSize: 22,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.white,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // ═══════════════════════════════════
            // COMPONENTS TABLE
            // ═══════════════════════════════════
            pw.Text(
              'Wood Components Breakdown',
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue800,
              ),
            ),
            pw.SizedBox(height: 8),

            pw.Table(
              border: pw.TableBorder.all(
                  color: PdfColors.grey300, width: 0.5),
              columnWidths: {
                0: const pw.FlexColumnWidth(2.5),
                1: const pw.FlexColumnWidth(2.5),
                2: const pw.FlexColumnWidth(1),
                3: const pw.FlexColumnWidth(1.5),
              },
              children: [
                pw.TableRow(
                  decoration:
                  pw.BoxDecoration(color: PdfColors.blue800),
                  children: [
                    _tableHeader('Wood Type'),
                    _tableHeader('Dimensions'),
                    _tableHeader('Quantity'),
                    _tableHeader('CFT'),
                  ],
                ),
                ...components.asMap().entries.map((entry) {
                  final i = entry.key;
                  final component = entry.value;
                  return pw.TableRow(
                    decoration: pw.BoxDecoration(
                      color: i % 2 == 0
                          ? PdfColors.white
                          : PdfColors.grey50,
                    ),
                    children: [
                      _tableCell(component.woodType),
                      _tableCell(component.formattedSize),
                      _tableCell('${component.quantity} pcs'),
                      _tableCell(
                        component.cft.toStringAsFixed(2),
                        bold: true,
                      ),
                    ],
                  );
                }).toList(),
                pw.TableRow(
                  decoration: const pw.BoxDecoration(
                      color: PdfColors.blue100),
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(8),
                      child: pw.Text(
                        'TOTAL',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 11,
                          color: PdfColors.blue800,
                        ),
                      ),
                    ),
                    pw.Padding(
                        padding: const pw.EdgeInsets.all(8),
                        child: pw.Text('')),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(8),
                      child: pw.Text(
                        '${components.fold<int>(0, (s, c) => s + c.quantity)} pcs',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 11,
                          color: PdfColors.blue800,
                        ),
                      ),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(8),
                      child: pw.Text(
                        '${totalCft.toStringAsFixed(2)} CFT',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 11,
                          color: PdfColors.blue800,
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),

            pw.SizedBox(height: 20),

            // ═══════════════════════════════════
            // FORMULA BOX
            // ═══════════════════════════════════
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(8),
                border:
                pw.Border.all(color: PdfColors.grey300),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'CFT Formula:',
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 10,
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'CFT = (Length ft × Width inch × Thickness inch) ÷ 144 × Quantity',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 15),

            // Footer
            pw.Row(
              mainAxisAlignment:
              pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by $companyName',
                  style: pw.TextStyle(
                      fontSize: 9, color: PdfColors.grey600),
                ),
                pw.Text(
                  'Powered by WoodRate Pro • NishantCreation',
                  style: pw.TextStyle(
                      fontSize: 9, color: PdfColors.grey600),
                ),
              ],
            ),
          ];
        },
      ),
    );

    return pdf;
  }

  static pw.Widget _tableHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 10,
          color: PdfColors.white,
        ),
      ),
    );
  }

  static pw.Widget _tableCell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight:
          bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }
}