import 'dart:io';
import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/order.dart';
import '../services/company_service.dart';
import '../providers/auth_provider.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class PDFGenerator {
  // Save to Downloads folder
  static Future<File> _saveToDownloads(
      Uint8List bytes, String fileName) async {
    try {
      // Try Downloads folder first
      Directory? downloadsDir;

      if (Platform.isAndroid) {
        downloadsDir = Directory('/storage/emulated/0/Download');
        if (!await downloadsDir.exists()) {
          downloadsDir = await getExternalStorageDirectory();
        }
      } else {
        downloadsDir = await getApplicationDocumentsDirectory();
      }

      downloadsDir ??= await getApplicationDocumentsDirectory();

      if (!await downloadsDir.exists()) {
        await downloadsDir.create(recursive: true);
      }

      final file = File('${downloadsDir.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file;
    } catch (e) {
      // Fallback to app documents
      final appDir = await getApplicationDocumentsDirectory();
      final file = File('${appDir.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file;
    }
  }

  static Future<File> generate(Order order,
      {BuildContext? context}) async {
    final pdf = await _createPDF(order, context: context);
    final bytes = await pdf.save();
    final fileName =
        'WoodRatePro_${order.orderId}_${DateFormat('ddMMyyyy').format(order.date)}.pdf';
    return _saveToDownloads(bytes, fileName);
  }

  static Future<Uint8List> generateBytes(Order order,
      {BuildContext? context}) async {
    final pdf = await _createPDF(order, context: context);
    return pdf.save();
  }

  // Share via WhatsApp or any app
  static Future<void> shareOrder(Order order,
      {BuildContext? context}) async {
    final bytes = await generateBytes(order, context: context);
    final tempDir = await getTemporaryDirectory();
    final fileName =
        'WoodRatePro_${order.orderId}_${DateFormat('ddMMyyyy').format(order.date)}.pdf';
    final file = File('${tempDir.path}/$fileName');
    await file.writeAsBytes(bytes);

    await Share.shareXFiles(
      [XFile(file.path)],
      text:
      'Cost Estimate for ${order.itemDescription}\nTotal: ₹${order.total.toStringAsFixed(2)}\nGenerated by WoodRate Pro',
      subject: 'Cost Estimate - ${order.itemDescription}',
    );
  }

  static Future<pw.Document> _createPDF(Order order,
      {BuildContext? context}) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd-MM-yyyy HH:mm');
    final currencyFormat = NumberFormat('#,##,##0.00', 'en_IN');

    // Load company details from Firebase
    String companyName = 'WoodRate Pro';
    String companyAddress = '';
    String companyPhone = '';
    String companyGstin = '';
    String ownerName = '';

    if (context != null) {
      try {
        final authProvider =
        Provider.of<AuthProvider>(context, listen: false);
        final company = authProvider.currentCompany;
        if (company != null) {
          companyName = company.companyName;
          companyAddress = company.address;
          companyPhone = company.phone;
          companyGstin = company.gstin ?? '';
          ownerName = company.ownerName;
        }
      } catch (e) {
        // use defaults
      }
    }

    String formatCurrency(double amount) {
      return 'Rs.${currencyFormat.format(amount)}';
    }

    double woodSubtotal = order.woodTotal;
    double otherCosts = order.labour +
        order.hardware +
        order.factory +
        order.additionalChargesTotal;
    double subtotalBeforeProfit = woodSubtotal + otherCosts;
    double profitPercentage = subtotalBeforeProfit > 0
        ? (order.profit / subtotalBeforeProfit) * 100
        : 0;

    pw.ImageProvider? itemImage;
    if (order.itemImagePath != null) {
      try {
        final imageFile = File(order.itemImagePath!);
        if (await imageFile.exists()) {
          final imageBytes = await imageFile.readAsBytes();
          itemImage = pw.MemoryImage(imageBytes);
        }
      } catch (e) {
        itemImage = null;
      }
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return [
            // ═══════════════════════════════════
            // HEADER - Company Info + Branding
            // ═══════════════════════════════════
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(20),
              decoration: pw.BoxDecoration(
                gradient: const pw.LinearGradient(
                  colors: [PdfColors.brown800, PdfColors.brown600],
                ),
                borderRadius: pw.BorderRadius.circular(12),
              ),
              child: pw.Row(
                mainAxisAlignment:
                pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  // Company Details
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment:
                      pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          companyName,
                          style: pw.TextStyle(
                            fontSize: 24,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.white,
                          ),
                        ),
                        if (ownerName.isNotEmpty) ...[
                          pw.SizedBox(height: 4),
                          pw.Text(
                            ownerName,
                            style: const pw.TextStyle(
                              fontSize: 12,
                              color: PdfColors.white,
                            ),
                          ),
                        ],
                        if (companyPhone.isNotEmpty) ...[
                          pw.SizedBox(height: 4),
                          pw.Text(
                            'Ph: $companyPhone',
                            style: const pw.TextStyle(
                              fontSize: 11,
                              color: PdfColors.white,
                            ),
                          ),
                        ],
                        if (companyAddress.isNotEmpty) ...[
                          pw.SizedBox(height: 4),
                          pw.Text(
                            companyAddress,
                            style: const pw.TextStyle(
                              fontSize: 10,
                              color: PdfColors.white,
                            ),
                          ),
                        ],
                        if (companyGstin.isNotEmpty) ...[
                          pw.SizedBox(height: 4),
                          pw.Text(
                            'GSTIN: $companyGstin',
                            style: const pw.TextStyle(
                              fontSize: 10,
                              color: PdfColors.white,
                            ),
                          ),
                        ],
                      ],
                    ),
                  ),
                  // Document Type Badge
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(
                        horizontal: 16, vertical: 8),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.white,
                      borderRadius: pw.BorderRadius.circular(8),
                    ),
                    child: pw.Column(
                      crossAxisAlignment:
                      pw.CrossAxisAlignment.center,
                      children: [
                        pw.Text(
                          'COST ESTIMATE',
                          style: pw.TextStyle(
                            fontSize: 14,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.brown800,
                          ),
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(
                          'WoodRate Pro',
                          style: pw.TextStyle(
                            fontSize: 10,
                            color: PdfColors.brown600,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // ═══════════════════════════════════
            // ORDER INFO
            // ═══════════════════════════════════
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(15),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey50,
                borderRadius: pw.BorderRadius.circular(8),
                border:
                pw.Border.all(color: PdfColors.grey300),
              ),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Expanded(
                    flex: 3,
                    child: pw.Column(
                      crossAxisAlignment:
                      pw.CrossAxisAlignment.start,
                      children: [
                        pw.Row(
                          mainAxisAlignment:
                          pw.MainAxisAlignment.spaceBetween,
                          children: [
                            pw.Column(
                              crossAxisAlignment:
                              pw.CrossAxisAlignment.start,
                              children: [
                                pw.Text(
                                  'Order ID: ${order.orderId}',
                                  style: pw.TextStyle(
                                    fontSize: 14,
                                    fontWeight:
                                    pw.FontWeight.bold,
                                  ),
                                ),
                                pw.SizedBox(height: 4),
                                pw.Text(
                                  'Date: ${dateFormat.format(order.date)}',
                                  style: const pw.TextStyle(
                                      fontSize: 11),
                                ),
                              ],
                            ),
                            pw.Container(
                              padding:
                              const pw.EdgeInsets.symmetric(
                                  horizontal: 12,
                                  vertical: 6),
                              decoration: pw.BoxDecoration(
                                color: PdfColors.green100,
                                borderRadius:
                                pw.BorderRadius.circular(12),
                                border: pw.Border.all(
                                    color: PdfColors.green400),
                              ),
                              child: pw.Text(
                                'CONFIRMED',
                                style: pw.TextStyle(
                                  fontSize: 10,
                                  fontWeight: pw.FontWeight.bold,
                                  color: PdfColors.green800,
                                ),
                              ),
                            ),
                          ],
                        ),
                        pw.SizedBox(height: 10),
                        pw.Container(
                          width: double.infinity,
                          padding: const pw.EdgeInsets.all(10),
                          decoration: pw.BoxDecoration(
                            color: PdfColors.blue50,
                            borderRadius:
                            pw.BorderRadius.circular(6),
                            border: pw.Border.all(
                                color: PdfColors.blue200),
                          ),
                          child: pw.Column(
                            crossAxisAlignment:
                            pw.CrossAxisAlignment.start,
                            children: [
                              pw.Text(
                                'Item Description:',
                                style: pw.TextStyle(
                                  fontSize: 10,
                                  fontWeight: pw.FontWeight.bold,
                                  color: PdfColors.blue800,
                                ),
                              ),
                              pw.SizedBox(height: 4),
                              pw.Text(
                                order.itemDescription,
                                style: pw.TextStyle(
                                  fontSize: 13,
                                  fontWeight: pw.FontWeight.bold,
                                  color: PdfColors.blue900,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                  if (itemImage != null) ...[
                    pw.SizedBox(width: 15),
                    pw.Container(
                      width: 110,
                      height: 110,
                      decoration: pw.BoxDecoration(
                        border: pw.Border.all(
                            color: PdfColors.grey400),
                        borderRadius:
                        pw.BorderRadius.circular(6),
                      ),
                      child: pw.Image(itemImage,
                          fit: pw.BoxFit.cover),
                    ),
                  ],
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // ═══════════════════════════════════
            // WOOD COMPONENTS TABLE
            // ═══════════════════════════════════
            pw.Text(
              'Wood Components',
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.brown800,
              ),
            ),
            pw.SizedBox(height: 8),

            pw.Table(
              border: pw.TableBorder.all(
                  color: PdfColors.grey300, width: 0.5),
              columnWidths: {
                0: const pw.FlexColumnWidth(2),
                1: const pw.FlexColumnWidth(2),
                2: const pw.FlexColumnWidth(1.2),
                3: const pw.FlexColumnWidth(0.8),
                4: const pw.FlexColumnWidth(1),
                5: const pw.FlexColumnWidth(1.2),
              },
              children: [
                // Header
                pw.TableRow(
                  decoration: pw.BoxDecoration(
                      color: PdfColors.brown800),
                  children: [
                    _tableHeader('Wood Type'),
                    _tableHeader('Dimensions'),
                    _tableHeader('Rate/CFT'),
                    _tableHeader('Qty'),
                    _tableHeader('CFT'),
                    _tableHeader('Amount'),
                  ],
                ),
                // Data rows
                ...order.components
                    .asMap()
                    .entries
                    .map((entry) {
                  final i = entry.key;
                  final component = entry.value;
                  final isEven = i % 2 == 0;
                  return pw.TableRow(
                    decoration: pw.BoxDecoration(
                      color: isEven
                          ? PdfColors.white
                          : PdfColors.grey50,
                    ),
                    children: [
                      _tableCell(component.woodType),
                      _tableCell(component.formattedSize),
                      _tableCell(
                          formatCurrency(component.ratePerCft)),
                      _tableCell(
                          component.quantity.toString()),
                      _tableCell(
                          component.cft.toStringAsFixed(2)),
                      _tableCell(
                        formatCurrency(component.totalCost),
                        bold: true,
                      ),
                    ],
                  );
                }).toList(),
                // Subtotal row
                pw.TableRow(
                  decoration: const pw.BoxDecoration(
                      color: PdfColors.brown100),
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        'Wood Subtotal',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 10,
                          color: PdfColors.brown800,
                        ),
                      ),
                    ),
                    pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text('')),
                    pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text('')),
                    pw.Padding(
                        padding: const pw.EdgeInsets.all(6),
                        child: pw.Text('')),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        order.totalCft.toStringAsFixed(2),
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 10,
                          color: PdfColors.brown800,
                        ),
                      ),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(
                        formatCurrency(woodSubtotal),
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 10,
                          color: PdfColors.brown800,
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),

            pw.SizedBox(height: 20),

            // ═══════════════════════════════════
            // COST SUMMARY
            // ═══════════════════════════════════
            pw.Text(
              'Cost Summary',
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.brown800,
              ),
            ),
            pw.SizedBox(height: 8),

            pw.Container(
              width: double.infinity,
              decoration: pw.BoxDecoration(
                border:
                pw.Border.all(color: PdfColors.grey300),
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                children: [
                  _summaryRow(
                      'Wood Components', woodSubtotal, formatCurrency),
                  _summaryDivider(),
                  _summaryRow(
                      'Labour Charges', order.labour, formatCurrency),
                  _summaryRow(
                      'Hardware Costs', order.hardware, formatCurrency),
                  _summaryRow('Factory Overheads', order.factory,
                      formatCurrency),
                  if (order.additionalCharges.isNotEmpty) ...[
                    _summaryDivider(),
                    pw.Container(
                      width: double.infinity,
                      padding: const pw.EdgeInsets.all(8),
                      color: PdfColors.orange50,
                      child: pw.Text(
                        'Other Charges',
                        style: pw.TextStyle(
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 11,
                          color: PdfColors.orange800,
                        ),
                      ),
                    ),
                    ...order.additionalCharges
                        .map((charge) => _summaryRow(
                        charge['name'] as String,
                        charge['amount'] as double,
                        formatCurrency))
                        .toList(),
                    _summaryRow(
                      'Additional Total',
                      order.additionalChargesTotal,
                      formatCurrency,
                      isBold: true,
                      bgColor: PdfColors.orange100,
                    ),
                  ],
                  _summaryDivider(),
                  _summaryRow('Subtotal Before Profit',
                      subtotalBeforeProfit, formatCurrency,
                      isBold: true),
                  _summaryRow(
                      'Profit (${profitPercentage.toStringAsFixed(1)}%)',
                      order.profit,
                      formatCurrency),
                  // Total row
                  pw.Container(
                    width: double.infinity,
                    padding: const pw.EdgeInsets.all(12),
                    decoration: const pw.BoxDecoration(
                      color: PdfColors.brown800,
                      borderRadius: pw.BorderRadius.only(
                        bottomLeft: pw.Radius.circular(8),
                        bottomRight: pw.Radius.circular(8),
                      ),
                    ),
                    child: pw.Row(
                      mainAxisAlignment:
                      pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text(
                          'TOTAL ESTIMATED COST',
                          style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold,
                            fontSize: 14,
                            color: PdfColors.white,
                          ),
                        ),
                        pw.Text(
                          formatCurrency(order.total),
                          style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold,
                            fontSize: 16,
                            color: PdfColors.yellow,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // ═══════════════════════════════════
            // NOTES & FOOTER
            // ═══════════════════════════════════
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(8),
                border:
                pw.Border.all(color: PdfColors.grey300),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Terms & Notes:',
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 11,
                    ),
                  ),
                  pw.SizedBox(height: 5),
                  pw.Text(
                    '• This is an estimated cost for ${order.itemDescription}.',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                  pw.Text(
                    '• Actual costs may vary based on market conditions.',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                  pw.Text(
                    '• All prices are in Indian Rupees (₹).',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                  pw.Text(
                    '• This estimate is valid for 30 days from the date of issue.',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 15),

            pw.Row(
              mainAxisAlignment:
              pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by $companyName',
                  style: pw.TextStyle(
                      fontSize: 9, color: PdfColors.grey600),
                ),
                pw.Text(
                  'Powered by WoodRate Pro • NishantCreation',
                  style: pw.TextStyle(
                      fontSize: 9, color: PdfColors.grey600),
                ),
                pw.Text(
                  dateFormat.format(DateTime.now()),
                  style: pw.TextStyle(
                      fontSize: 9, color: PdfColors.grey600),
                ),
              ],
            ),
          ];
        },
      ),
    );

    return pdf;
  }

  // Helper widgets
  static pw.Widget _tableHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 9,
          color: PdfColors.white,
        ),
      ),
    );
  }

  static pw.Widget _tableCell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight:
          bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }

  static pw.Widget _summaryRow(
      String label,
      double amount,
      String Function(double) formatCurrency, {
        bool isBold = false,
        PdfColor? bgColor,
      }) {
    return pw.Container(
      color: bgColor,
      padding: const pw.EdgeInsets.symmetric(
          horizontal: 12, vertical: 7),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: isBold ? 12 : 11,
              fontWeight: isBold
                  ? pw.FontWeight.bold
                  : pw.FontWeight.normal,
            ),
          ),
          pw.Text(
            formatCurrency(amount),
            style: pw.TextStyle(
              fontSize: isBold ? 12 : 11,
              fontWeight: isBold
                  ? pw.FontWeight.bold
                  : pw.FontWeight.normal,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _summaryDivider() {
    return pw.Container(
      height: 0.5,
      color: PdfColors.grey300,
    );
  }
}