import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/order.dart';
import '../providers/auth_provider.dart';

class PDFGenerator {
  static Future<File> _saveToDownloads(
      Uint8List bytes, String fileName) async {
    try {
      Directory? downloadsDir;
      if (Platform.isAndroid) {
        downloadsDir =
            Directory('/storage/emulated/0/Download');
        if (!await downloadsDir.exists()) {
          downloadsDir = await getExternalStorageDirectory();
        }
      } else {
        downloadsDir = await getApplicationDocumentsDirectory();
      }
      downloadsDir ??= await getApplicationDocumentsDirectory();
      if (!await downloadsDir.exists()) {
        await downloadsDir.create(recursive: true);
      }
      final file = File('${downloadsDir.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file;
    } catch (e) {
      final appDir = await getApplicationDocumentsDirectory();
      final file = File('${appDir.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file;
    }
  }

  static Future<File> generate(Order order,
      {BuildContext? context}) async {
    final pdf = await _createPDF(order, context: context);
    final bytes = await pdf.save();
    final fileName =
        'WoodRatePro_${order.orderId}_${DateFormat('ddMMyyyy').format(order.date)}.pdf';
    return _saveToDownloads(bytes, fileName);
  }

  static Future<Uint8List> generateBytes(Order order,
      {BuildContext? context}) async {
    final pdf = await _createPDF(order, context: context);
    return pdf.save();
  }

  static Future<void> shareOrder(Order order,
      {BuildContext? context}) async {
    final bytes =
    await generateBytes(order, context: context);
    final tempDir = await getTemporaryDirectory();
    final fileName =
        'WoodRatePro_${order.orderId}_${DateFormat('ddMMyyyy').format(order.date)}.pdf';
    final file = File('${tempDir.path}/$fileName');
    await file.writeAsBytes(bytes);
    await Share.shareXFiles(
      [XFile(file.path)],
      text:
      'Cost Estimate for ${order.itemDescription}\nTotal: Rs.${order.total.toStringAsFixed(2)}\nGenerated by WoodRate Pro',
      subject: 'Cost Estimate - ${order.itemDescription}',
    );
  }

  static Future<pw.Document> _createPDF(Order order,
      {BuildContext? context}) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd-MM-yyyy HH:mm');
    final currencyFormat =
    NumberFormat('#,##,##0.00', 'en_IN');

    String companyName = 'WoodRate Pro';
    String companyAddress = '';
    String companyPhone = '';
    String companyGstin = '';
    String ownerName = '';

    if (context != null) {
      try {
        final authProvider =
        Provider.of<AuthProvider>(context, listen: false);
        final company = authProvider.currentCompany;
        if (company != null) {
          companyName = company.companyName;
          companyAddress = company.address;
          companyPhone = company.phone;
          companyGstin = company.gstin ?? '';
          ownerName = company.ownerName;
        }
      } catch (e) {}
    }

    String fc(double amount) =>
        'Rs.${currencyFormat.format(amount)}';

    double woodSubtotal = order.woodTotal;
    double otherCosts = order.labour +
        order.hardware +
        order.factory +
        order.additionalChargesTotal;
    double subtotalBeforeProfit = woodSubtotal + otherCosts;
    double profitPct = subtotalBeforeProfit > 0
        ? (order.profit / subtotalBeforeProfit) * 100
        : 0;

    pw.ImageProvider? itemImage;
    if (order.itemImagePath != null) {
      try {
        final imageFile = File(order.itemImagePath!);
        if (await imageFile.exists()) {
          itemImage =
              pw.MemoryImage(await imageFile.readAsBytes());
        }
      } catch (_) {}
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context ctx) => [
          // ══════════════════════════════
          // HEADER
          // ══════════════════════════════
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(
                horizontal: 16, vertical: 12),
            decoration: pw.BoxDecoration(
              gradient: const pw.LinearGradient(colors: [
                PdfColors.brown800,
                PdfColors.brown600
              ]),
              borderRadius: pw.BorderRadius.circular(10),
            ),
            child: pw.Row(
              mainAxisAlignment:
              pw.MainAxisAlignment.spaceBetween,
              crossAxisAlignment:
              pw.CrossAxisAlignment.center,
              children: [
                pw.Column(
                  crossAxisAlignment:
                  pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(companyName,
                        style: pw.TextStyle(
                            fontSize: 20,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.white)),
                    if (ownerName.isNotEmpty)
                      pw.Text(ownerName,
                          style: const pw.TextStyle(
                              fontSize: 11,
                              color: PdfColors.white)),
                    if (companyPhone.isNotEmpty)
                      pw.Text('Ph: $companyPhone',
                          style: const pw.TextStyle(
                              fontSize: 10,
                              color: PdfColors.white)),
                    if (companyAddress.isNotEmpty)
                      pw.Text(companyAddress,
                          style: const pw.TextStyle(
                              fontSize: 9,
                              color: PdfColors.white)),
                    if (companyGstin.isNotEmpty)
                      pw.Text('GSTIN: $companyGstin',
                          style: const pw.TextStyle(
                              fontSize: 9,
                              color: PdfColors.white)),
                  ],
                ),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 12, vertical: 6),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.white,
                    borderRadius:
                    pw.BorderRadius.circular(6),
                  ),
                  child: pw.Column(
                    crossAxisAlignment:
                    pw.CrossAxisAlignment.center,
                    children: [
                      pw.Text('COST ESTIMATE',
                          style: pw.TextStyle(
                              fontSize: 12,
                              fontWeight: pw.FontWeight.bold,
                              color: PdfColors.brown800)),
                      pw.Text('WoodRate Pro',
                          style: pw.TextStyle(
                              fontSize: 8,
                              color: PdfColors.brown600)),
                    ],
                  ),
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 12),

          // ══════════════════════════════
          // ORDER INFO + IMAGE (SAME ROW)
          // ══════════════════════════════
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey50,
              borderRadius: pw.BorderRadius.circular(8),
              border:
              pw.Border.all(color: PdfColors.grey300),
            ),
            child: pw.Row(
              crossAxisAlignment:
              pw.CrossAxisAlignment.start,
              children: [
                // Left: order details
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment:
                    pw.CrossAxisAlignment.start,
                    children: [
                      // Order ID + Status badge
                      pw.Row(
                        mainAxisAlignment:
                        pw.MainAxisAlignment.spaceBetween,
                        children: [
                          pw.Text(
                            'Order: ${order.orderId}',
                            style: pw.TextStyle(
                                fontSize: 12,
                                fontWeight:
                                pw.FontWeight.bold),
                          ),
                          pw.Container(
                            padding: const pw.EdgeInsets
                                .symmetric(
                                horizontal: 8, vertical: 3),
                            decoration: pw.BoxDecoration(
                              color: PdfColors.green100,
                              borderRadius:
                              pw.BorderRadius.circular(
                                  10),
                              border: pw.Border.all(
                                  color: PdfColors.green400),
                            ),
                            child: pw.Text(
                              order.status?.toUpperCase() ??
                                  'CONFIRMED',
                              style: pw.TextStyle(
                                  fontSize: 8,
                                  fontWeight:
                                  pw.FontWeight.bold,
                                  color: PdfColors.green800),
                            ),
                          ),
                        ],
                      ),

                      pw.SizedBox(height: 4),
                      pw.Text(
                        'Date: ${dateFormat.format(order.date)}',
                        style:
                        const pw.TextStyle(fontSize: 10),
                      ),

                      pw.SizedBox(height: 6),

                      // Item description box
                      pw.Container(
                        width: double.infinity,
                        padding:
                        const pw.EdgeInsets.all(8),
                        decoration: pw.BoxDecoration(
                          color: PdfColors.blue50,
                          borderRadius:
                          pw.BorderRadius.circular(5),
                          border: pw.Border.all(
                              color: PdfColors.blue200),
                        ),
                        child: pw.Column(
                          crossAxisAlignment:
                          pw.CrossAxisAlignment.start,
                          children: [
                            pw.Text('Item:',
                                style: pw.TextStyle(
                                    fontSize: 9,
                                    fontWeight:
                                    pw.FontWeight.bold,
                                    color:
                                    PdfColors.blue800)),
                            pw.SizedBox(height: 2),
                            pw.Text(
                              order.itemDescription,
                              style: pw.TextStyle(
                                  fontSize: 12,
                                  fontWeight:
                                  pw.FontWeight.bold,
                                  color: PdfColors.blue900),
                            ),
                          ],
                        ),
                      ),

                      // Client info
                      if (order.clientName != null &&
                          order.clientName!
                              .isNotEmpty) ...[
                        pw.SizedBox(height: 5),
                        pw.Row(children: [
                          pw.Text('Client: ',
                              style: pw.TextStyle(
                                  fontWeight:
                                  pw.FontWeight.bold,
                                  fontSize: 10)),
                          pw.Text(order.clientName!,
                              style: const pw.TextStyle(
                                  fontSize: 10)),
                        ]),
                      ],
                      if (order.clientCompany != null &&
                          order.clientCompany!
                              .isNotEmpty) ...[
                        pw.SizedBox(height: 3),
                        pw.Row(children: [
                          pw.Text('Company: ',
                              style: pw.TextStyle(
                                  fontWeight:
                                  pw.FontWeight.bold,
                                  fontSize: 10)),
                          pw.Text(order.clientCompany!,
                              style: const pw.TextStyle(
                                  fontSize: 10)),
                        ]),
                      ],

                      // Notes
                      if (order.notes != null &&
                          order.notes!.isNotEmpty) ...[
                        pw.SizedBox(height: 5),
                        pw.Container(
                          width: double.infinity,
                          padding:
                          const pw.EdgeInsets.all(6),
                          decoration: pw.BoxDecoration(
                            color: PdfColors.purple50,
                            borderRadius:
                            pw.BorderRadius.circular(5),
                            border: pw.Border.all(
                                color: PdfColors.purple200),
                          ),
                          child: pw.Column(
                            crossAxisAlignment:
                            pw.CrossAxisAlignment.start,
                            children: [
                              pw.Text('Notes:',
                                  style: pw.TextStyle(
                                      fontWeight:
                                      pw.FontWeight.bold,
                                      fontSize: 9,
                                      color: PdfColors
                                          .purple800)),
                              pw.SizedBox(height: 2),
                              pw.Text(order.notes!,
                                  style: const pw.TextStyle(
                                      fontSize: 9)),
                            ],
                          ),
                        ),
                      ],
                    ],
                  ),
                ),

                // Right: image
                if (itemImage != null) ...[
                  pw.SizedBox(width: 12),
                  pw.Container(
                    width: 100,
                    height: 100,
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(
                          color: PdfColors.grey400),
                      borderRadius:
                      pw.BorderRadius.circular(6),
                    ),
                    child: pw.Image(itemImage,
                        fit: pw.BoxFit.cover),
                  ),
                ],
              ],
            ),
          ),

          pw.SizedBox(height: 12),

          // ══════════════════════════════
          // WOOD COMPONENTS TABLE
          // ══════════════════════════════
          pw.Text('Wood Components',
              style: pw.TextStyle(
                  fontSize: 13,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.brown800)),
          pw.SizedBox(height: 6),

          pw.Table(
            border: pw.TableBorder.all(
                color: PdfColors.grey300, width: 0.5),
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(2),
              2: const pw.FlexColumnWidth(1.2),
              3: const pw.FlexColumnWidth(0.7),
              4: const pw.FlexColumnWidth(0.9),
              5: const pw.FlexColumnWidth(1.2),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(
                    color: PdfColors.brown800),
                children: [
                  _th('Wood Type'),
                  _th('Dimensions'),
                  _th('Rate/CFT'),
                  _th('Qty'),
                  _th('CFT'),
                  _th('Amount'),
                ],
              ),
              ...order.components.asMap().entries.map((e) {
                final i = e.key;
                final c = e.value;
                return pw.TableRow(
                  decoration: pw.BoxDecoration(
                      color: i % 2 == 0
                          ? PdfColors.white
                          : PdfColors.grey50),
                  children: [
                    _td(c.woodType),
                    _td(c.formattedSize),
                    _td(fc(c.ratePerCft)),
                    _td(c.quantity.toString()),
                    _td(c.cft.toStringAsFixed(2)),
                    _td(fc(c.totalCost), bold: true),
                  ],
                );
              }).toList(),
              // Subtotal row
              pw.TableRow(
                decoration: const pw.BoxDecoration(
                    color: PdfColors.brown100),
                children: [
                  _tdBold('Subtotal', PdfColors.brown800),
                  _td(''),
                  _td(''),
                  _td(''),
                  _tdBold(
                      '${order.totalCft.toStringAsFixed(2)} CFT',
                      PdfColors.brown800),
                  _tdBold(fc(woodSubtotal),
                      PdfColors.brown800),
                ],
              ),
            ],
          ),

          pw.SizedBox(height: 12),

          // ══════════════════════════════
          // COST SUMMARY
          // ══════════════════════════════
          pw.Text('Cost Summary',
              style: pw.TextStyle(
                  fontSize: 13,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.brown800)),
          pw.SizedBox(height: 6),

          pw.Container(
            width: double.infinity,
            decoration: pw.BoxDecoration(
              border:
              pw.Border.all(color: PdfColors.grey300),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(
              children: [
                _sr('Wood Components', woodSubtotal, fc),
                _div(),
                _sr('Labour', order.labour, fc),
                _sr('Hardware', order.hardware, fc),
                _sr('Factory', order.factory, fc),
                if (order.additionalCharges
                    .isNotEmpty) ...[
                  _div(),
                  pw.Container(
                    width: double.infinity,
                    padding:
                    const pw.EdgeInsets.symmetric(
                        horizontal: 10, vertical: 5),
                    color: PdfColors.orange50,
                    child: pw.Text('Other Charges',
                        style: pw.TextStyle(
                            fontWeight: pw.FontWeight.bold,
                            fontSize: 10,
                            color: PdfColors.orange800)),
                  ),
                  ...order.additionalCharges
                      .map((ch) => _sr(
                      ch['name'] as String,
                      ch['amount'] as double,
                      fc))
                      .toList(),
                  _sr('Additional Total',
                      order.additionalChargesTotal, fc,
                      isBold: true,
                      bg: PdfColors.orange100),
                ],
                _div(),
                _sr('Subtotal Before Profit',
                    subtotalBeforeProfit, fc,
                    isBold: true),
                _sr(
                    'Profit (${profitPct.toStringAsFixed(1)}%)',
                    order.profit,
                    fc),
                // Total
                pw.Container(
                  width: double.infinity,
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 12, vertical: 10),
                  decoration: const pw.BoxDecoration(
                    color: PdfColors.brown800,
                    borderRadius: pw.BorderRadius.only(
                      bottomLeft: pw.Radius.circular(8),
                      bottomRight: pw.Radius.circular(8),
                    ),
                  ),
                  child: pw.Row(
                    mainAxisAlignment:
                    pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text('TOTAL ESTIMATED COST',
                          style: pw.TextStyle(
                              fontWeight: pw.FontWeight.bold,
                              fontSize: 13,
                              color: PdfColors.white)),
                      pw.Text(fc(order.total),
                          style: pw.TextStyle(
                              fontWeight: pw.FontWeight.bold,
                              fontSize: 15,
                              color: PdfColors.yellow)),
                    ],
                  ),
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 12),

          // ══════════════════════════════
          // TERMS & FOOTER
          // ══════════════════════════════
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(6),
              border:
              pw.Border.all(color: PdfColors.grey300),
            ),
            child: pw.Column(
              crossAxisAlignment:
              pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Terms & Notes:',
                    style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 9)),
                pw.SizedBox(height: 3),
                pw.Text(
                    '• Estimated cost for ${order.itemDescription}. Actual costs may vary.',
                    style: const pw.TextStyle(fontSize: 8)),
                pw.Text(
                    '• All prices in Indian Rupees. Valid for 30 days.',
                    style: const pw.TextStyle(fontSize: 8)),
              ],
            ),
          ),

          pw.SizedBox(height: 8),

          pw.Row(
            mainAxisAlignment:
            pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated by $companyName',
                  style: pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey600)),
              pw.Text(
                  'WoodRate Pro • NishantCreation',
                  style: pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey600)),
              pw.Text(
                  dateFormat.format(DateTime.now()),
                  style: pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey600)),
            ],
          ),
        ],
      ),
    );

    return pdf;
  }

  // Table header cell
  static pw.Widget _th(String text) => pw.Padding(
    padding: const pw.EdgeInsets.all(5),
    child: pw.Text(text,
        style: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            fontSize: 8,
            color: PdfColors.white)),
  );

  // Table data cell
  static pw.Widget _td(String text,
      {bool bold = false}) =>
      pw.Padding(
        padding: const pw.EdgeInsets.all(5),
        child: pw.Text(text,
            style: pw.TextStyle(
                fontSize: 8,
                fontWeight: bold
                    ? pw.FontWeight.bold
                    : pw.FontWeight.normal)),
      );

  // Table bold colored cell
  static pw.Widget _tdBold(String text, PdfColor color) =>
      pw.Padding(
        padding: const pw.EdgeInsets.all(5),
        child: pw.Text(text,
            style: pw.TextStyle(
                fontSize: 8,
                fontWeight: pw.FontWeight.bold,
                color: color)),
      );

  // Summary row
  static pw.Widget _sr(
      String label,
      double amount,
      String Function(double) fc, {
        bool isBold = false,
        PdfColor? bg,
      }) =>
      pw.Container(
        color: bg,
        padding: const pw.EdgeInsets.symmetric(
            horizontal: 10, vertical: 6),
        child: pw.Row(
          mainAxisAlignment:
          pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(label,
                style: pw.TextStyle(
                    fontSize: isBold ? 11 : 10,
                    fontWeight: isBold
                        ? pw.FontWeight.bold
                        : pw.FontWeight.normal)),
            pw.Text(fc(amount),
                style: pw.TextStyle(
                    fontSize: isBold ? 11 : 10,
                    fontWeight: isBold
                        ? pw.FontWeight.bold
                        : pw.FontWeight.normal)),
          ],
        ),
      );

  // Divider
  static pw.Widget _div() =>
      pw.Container(height: 0.5, color: PdfColors.grey300);
}